apiVersion: v1
kind: Secret
metadata:
  name: argoproj-https-creds
  labels:
    argocd.argoproj.io/secret-type: repo-creds
stringData:
  type: git
  url: {{ .Values.git.url }}
  password: {{ .Values.git.username }}
  username: {{ .Values.git.password }}