kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.metadata.name }}
  namespace: cicd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
